/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SosRouteImport } from './routes/sos'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as HospitalRouteImport } from './routes/hospital'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HospitalIndexRouteImport } from './routes/hospital.index'
import { Route as AppointmentsIndexRouteImport } from './routes/appointments.index'
import { Route as HospitalUploadRouteImport } from './routes/hospital.upload'
import { Route as HospitalAlertsRouteImport } from './routes/hospital.alerts'
import { Route as AppointmentsNewRouteImport } from './routes/appointments.new'
import { Route as AppointmentsIdRouteImport } from './routes/appointments.$id'

const SosRoute = SosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalRoute = HospitalRouteImport.update({
  id: '/hospital',
  path: '/hospital',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalIndexRoute = HospitalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HospitalRoute,
} as any)
const AppointmentsIndexRoute = AppointmentsIndexRouteImport.update({
  id: '/appointments/',
  path: '/appointments/',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalUploadRoute = HospitalUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => HospitalRoute,
} as any)
const HospitalAlertsRoute = HospitalAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => HospitalRoute,
} as any)
const AppointmentsNewRoute = AppointmentsNewRouteImport.update({
  id: '/appointments/new',
  path: '/appointments/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsIdRoute = AppointmentsIdRouteImport.update({
  id: '/appointments/$id',
  path: '/appointments/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/hospital': typeof HospitalRouteWithChildren
  '/profile': typeof ProfileRoute
  '/sos': typeof SosRoute
  '/appointments/$id': typeof AppointmentsIdRoute
  '/appointments/new': typeof AppointmentsNewRoute
  '/hospital/alerts': typeof HospitalAlertsRoute
  '/hospital/upload': typeof HospitalUploadRoute
  '/appointments/': typeof AppointmentsIndexRoute
  '/hospital/': typeof HospitalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/profile': typeof ProfileRoute
  '/sos': typeof SosRoute
  '/appointments/$id': typeof AppointmentsIdRoute
  '/appointments/new': typeof AppointmentsNewRoute
  '/hospital/alerts': typeof HospitalAlertsRoute
  '/hospital/upload': typeof HospitalUploadRoute
  '/appointments': typeof AppointmentsIndexRoute
  '/hospital': typeof HospitalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/hospital': typeof HospitalRouteWithChildren
  '/profile': typeof ProfileRoute
  '/sos': typeof SosRoute
  '/appointments/$id': typeof AppointmentsIdRoute
  '/appointments/new': typeof AppointmentsNewRoute
  '/hospital/alerts': typeof HospitalAlertsRoute
  '/hospital/upload': typeof HospitalUploadRoute
  '/appointments/': typeof AppointmentsIndexRoute
  '/hospital/': typeof HospitalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/hospital'
    | '/profile'
    | '/sos'
    | '/appointments/$id'
    | '/appointments/new'
    | '/hospital/alerts'
    | '/hospital/upload'
    | '/appointments/'
    | '/hospital/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/profile'
    | '/sos'
    | '/appointments/$id'
    | '/appointments/new'
    | '/hospital/alerts'
    | '/hospital/upload'
    | '/appointments'
    | '/hospital'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/hospital'
    | '/profile'
    | '/sos'
    | '/appointments/$id'
    | '/appointments/new'
    | '/hospital/alerts'
    | '/hospital/upload'
    | '/appointments/'
    | '/hospital/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  HospitalRoute: typeof HospitalRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  SosRoute: typeof SosRoute
  AppointmentsIdRoute: typeof AppointmentsIdRoute
  AppointmentsNewRoute: typeof AppointmentsNewRoute
  AppointmentsIndexRoute: typeof AppointmentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sos': {
      id: '/sos'
      path: '/sos'
      fullPath: '/sos'
      preLoaderRoute: typeof SosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital': {
      id: '/hospital'
      path: '/hospital'
      fullPath: '/hospital'
      preLoaderRoute: typeof HospitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital/': {
      id: '/hospital/'
      path: '/'
      fullPath: '/hospital/'
      preLoaderRoute: typeof HospitalIndexRouteImport
      parentRoute: typeof HospitalRoute
    }
    '/appointments/': {
      id: '/appointments/'
      path: '/appointments'
      fullPath: '/appointments/'
      preLoaderRoute: typeof AppointmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital/upload': {
      id: '/hospital/upload'
      path: '/upload'
      fullPath: '/hospital/upload'
      preLoaderRoute: typeof HospitalUploadRouteImport
      parentRoute: typeof HospitalRoute
    }
    '/hospital/alerts': {
      id: '/hospital/alerts'
      path: '/alerts'
      fullPath: '/hospital/alerts'
      preLoaderRoute: typeof HospitalAlertsRouteImport
      parentRoute: typeof HospitalRoute
    }
    '/appointments/new': {
      id: '/appointments/new'
      path: '/appointments/new'
      fullPath: '/appointments/new'
      preLoaderRoute: typeof AppointmentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments/$id': {
      id: '/appointments/$id'
      path: '/appointments/$id'
      fullPath: '/appointments/$id'
      preLoaderRoute: typeof AppointmentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface HospitalRouteChildren {
  HospitalAlertsRoute: typeof HospitalAlertsRoute
  HospitalUploadRoute: typeof HospitalUploadRoute
  HospitalIndexRoute: typeof HospitalIndexRoute
}

const HospitalRouteChildren: HospitalRouteChildren = {
  HospitalAlertsRoute: HospitalAlertsRoute,
  HospitalUploadRoute: HospitalUploadRoute,
  HospitalIndexRoute: HospitalIndexRoute,
}

const HospitalRouteWithChildren = HospitalRoute._addFileChildren(
  HospitalRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  HospitalRoute: HospitalRouteWithChildren,
  ProfileRoute: ProfileRoute,
  SosRoute: SosRoute,
  AppointmentsIdRoute: AppointmentsIdRoute,
  AppointmentsNewRoute: AppointmentsNewRoute,
  AppointmentsIndexRoute: AppointmentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
